"""Generate and validate the config-driven quip-miner runtime configuration."""
from __future__ import annotations
import os
import subprocess
from pathlib import Path
from typing import List, Optional, Tuple
from quip_android.config.models import AppConfig
from quip_android.utils.system import resolve_path

def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

def runtime_config_path(config: AppConfig) -> str:
    return resolve_path(config.miner.runtime_config_path)

def build_runtime_config(config: AppConfig, validators: List[str], workers: int, backend: str = "cpu", signer_key: Optional[str] = None) -> str:
    path = Path(runtime_config_path(config))
    path.parent.mkdir(parents=True, exist_ok=True)
    key_path = resolve_path(signer_key or config.signer.key_path)
    lines = ["# Generated by quip-android-aglais-node. Do not commit this file.", "", "[miner]", f"node_name = {_quote(config.miner.node_name or config.node.device_label)}", "validators = ["]
    lines.extend(f"  {_quote(endpoint)}," for endpoint in validators)
    lines.extend(["]", f"signer_key = {_quote(key_path)}"])
    if config.miner.faucet_url.strip():
        lines.append(f"faucet_url = {_quote(config.miner.faucet_url.strip())}")
    lines.append("")
    if backend == "cpu":
        lines.extend(["[cpu]", f"num_cpus = {max(1, int(workers))}"])
        if config.miner.cpu_binary.strip():
            lines.append(f"binary = {_quote(config.miner.cpu_binary.strip())}")
    elif backend == "gpu":
        lines.extend(["[cuda.0]", f"binary = {_quote(config.miner.gpu_binary)}"])
    else:
        raise ValueError(f"Unsupported backend: {backend}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass
    return str(path)

def validate_runtime_config(binary_path: str, config_path: str) -> Tuple[bool, str]:
    commands = [[binary_path, "resolve-modes", "--config", config_path], [binary_path, "resolve-mode", "--config", config_path]]
    last_output = ""
    for command in commands:
        try:
            result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, timeout=15)
            output = (result.stdout or "").strip()
            last_output = output
            if result.returncode == 0:
                return True, output or "config accepted"
        except (OSError, subprocess.TimeoutExpired) as exc:
            last_output = str(exc)
    return False, last_output or "quip-miner rejected the generated config"
